editor: source

execute:
  cache: false # "Danger Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/_post-render.R"

title: "LogoClim: WorldClim in NetLogo"
author: "Daniel Vartanian, Leandro Garcia, & Aline M. de Carvalho"
keyword: >
  Agent-Based Modeling, Climate Change, Climate Data Visualization,
  Climate Model Integration, Climate Projections, Climate Simulation,
  CMIP6, Complex Systems, Complexity Science, Data Interoperability,
  Environmental Sciences, Environmental Simulation, Future Climate Scenarios,
  Geospatial Analysis, Historical Climate Data, Models, NetLogo,
  Parallel Execution, R (Programming Language), Raster Data,
  Reproducible Research, Shared Socioeconomic Pathways, Simulations,
  Spatial Analysis, Spatial Resolution, SSSPs, Time Series, WorldClim
date: today
date-format: "YYYY-MM-DD"

website:
  favicon: images/sustentarea-icon.svg
  site-url: https://sustentarea.github.io/logoclim-article/
  repo-url: https://github.com/sustentarea/logoclim-article/
  issue-url: https://github.com/sustentarea/logoclim-article/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Sustentarea Research and Extension Group
  repo-branch: main
  repo-actions: [edit, source, issue]
  search: false
  navbar:
    title: false
    background: "#272B33"
    right:
      - icon: github
        href: https://github.com/sustentarea/logoclim-article/
        aria-label: GitHub

lightbox:
  match: auto
  effect: fade
  desc-position: bottom
  loop: false

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    locale: en
    language: en-us
    code-fold: false
    code-link: true
    code-tools: false
    df-print: paged
    fig-align: center
    cap-location: top
    lightbox: true
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    theme: [cosmo, scss/styles.scss, brand]
    other-links:
      - text: Sustentarea Website
        href: https://www.fsp.usp.br/sustentarea

google-scholar: true
bibliography: references.bib
