# # For testing
#
# Sys.setlocale(locale = "pt_BR.utf8")
# set_locale()
# get_locale()
# Sys.getlocale()
# Sys.getenv()
# Sys.getenv("LC_TIME")

# library(cli)
# library(stats)
# library(stringr)

set_locale <- function(
    session_id = Sys.time() |> as.character(), #nolint
    verbose = TRUE
  ) {
  locale_values <- c(
    "en_US.utf8", "en_US.UTF-8", "en_US", "en-US", "en",
    "English_United States"
  )

  # "LC_NAME", "LC_ADDRESS", "LC_TELEPHONE" == "invalid 'category' argument"

  locale_keys <-
    .LC.categories |>
    stringr::str_subset("LC_NUMERIC", negate = TRUE)

  env_keys <- c(
    .LC.categories[-1], "LC_NAME", "LC_ADDRESS", "LC_TELEPHONE",
    "LC_IDENTIFICATION"
  )

  # Sys.setlocale("LC_NUMERIC", "C")

  for (i in locale_values) {
    test <- Sys.setlocale(locale = i) |> suppressWarnings()

    if (!test == "" && Sys.getlocale("LC_TIME") == i) {
      for (j in locale_keys) Sys.setlocale(j, i)
      for (j in env_keys) do.call(Sys.setenv, as.list(stats::setNames(i, j)))
      Sys.setenv(LANG = "en")
      Sys.setenv(LANGUAGE = "en")

      break
    }
  }

  if (test == "" || !Sys.getlocale("LC_TIME") %in% locale_values) {
    cli::cli_alert_danger(
      paste0(
        "An error occurred while attempting to set the system locale to ",
        "English ({.strong Sys.setlocale(locale = 'en_US.utf8')}). ",
        "This step is crucial for the proper functioning of the data ",
        "wrangling functions. {.strong Without it, the data generated by ",
        "the pipeline will be {cli::col_red('invalid')}}! ",
        "Run {.strong {cli::col_blue('?Sys.setlocale')}} to investigate ",
        "the issue, or reach out to the thesis author for assistance."
      ),
      wrap = TRUE
    )

    cat("\n")

    cli::cli_alert(
      paste0(
        "Errors related to locale values are likely caused by differences in ",
        "how operating systems handle locale settings."
      ),
      wrap = TRUE
    )
  }

  if (Sys.getenv("SET_LOCALE_MESSAGES") == "") {
    Sys.setenv(SET_LOCALE_MESSAGES = session_id)

    if (isTRUE(verbose)) get_locale()
  }

  invisible()
}

# library(cli)

get_locale <- function() {
  cli::cli_alert(
    paste0(
      "The current system locale is:\n\n",
      "{Sys.getlocale()}\n\n"
    ),
    wrap = TRUE
  )

  env_keys <- c(
    .LC.categories[-1], "LC_NAME", "LC_ADDRESS", "LC_TELEPHONE",
    "LC_IDENTIFICATION"
  )

  cat("\n")

  env_values <- character()

  for (i in env_keys) {
    env_values <- c(env_values, paste0(i, "=", Sys.getenv(i)))
  }

  env_values <- paste(env_values, collapse = ";")

  cli::cli_alert(
    paste0(
      "The current values for the locale environment variables are:\n\n",
      "{env_values}"
    ),
    wrap = TRUE
  )

  cat("\n")

  cli::cli_alert(
    paste0(
      "The system locale needs to be set to {.strong English} to ensure ",
      "proper functionality ({.strong C} is ok too)."
    ),
    wrap = TRUE
  )

  invisible()
}
